"""Second-pass summary over the generated results.json (no new quadrature).

Writes outputs/summary.md: for every configuration, the discrepancy the referee is
about, the error bar of the reference it is measured against, and whether the
discrepancy is actually resolved by that error bar.  Kept separate from run.py so
that re-quoting never requires recomputing, and so every number in the README has a
generated source.

Run:
  wsl -e bash -lc 'cd <REPO> && PYTHONPATH=. python3 -u evidence/attribution_referee/summarize.py'
"""
import json
import os

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "outputs")
KCAL = 627.509474


def reference_uncertainty(conv):
    """Worst-case absolute error of the reference I_AB, from measured quantities."""
    order = max(c["last_change"] for k, c in conv.items()
                if k not in ("grid_level_ladder", "floor_study"))
    trunc = max(c["trunc_shift"] for k, c in conv.items()
                if k not in ("grid_level_ladder", "floor_study"))
    cross3d = max(abs(c["cyl_ab"][max(c["cyl_ab"], key=lambda x: int(x))]
                      - c["box_ab"][max(c["box_ab"], key=lambda x: int(x))])
                for k, c in conv.items() if k not in ("grid_level_ladder", "floor_study"))
    return order, trunc, cross3d


def main():
    with open(os.path.join(OUT, "results.json")) as fh:
        data = json.load(fh)
    rows = data["rows"]
    conv = data["convergence"]
    meta = data["meta"]
    L = ["# summary (generated by summarize.py from outputs/results.json)", ""]
    if conv:
        order, trunc, cross3d = reference_uncertainty(conv)
        unc = order + trunc + cross3d
        L.append("Reference error bar for I_AB, all three measured, not assumed:")
        L.append("- last-step change in the 5-D order ladders (worst config): "
                 "%.3e Ha" % order)
        L.append("- domain-truncation shift between f=5.0 and f=5.9 (worst): %.3e Ha"
                 % trunc)
        L.append("- Cartesian 3-D vs cylindrical 5-D disagreement at the top orders"
                 " (worst): %.3e Ha" % cross3d)
        L.append("- adopted combined uncertainty U = %.3e Ha = %.5f kcal/mol" %
                 (unc, unc * KCAL))
    else:
        L.append("(convergence phase skipped; no error bar available)")
        unc = float("nan")
    L.append("")
    L.append("Per configuration.  `d_headline` = package inter[0,1] (PySCF production"
             " grid) - exact I_AB.  `d_partition` = same node set, Becke block minus"
             " density-factor block, so the grid cancels.  `d_grid` = the density-"
             "factor block minus the exact reference, i.e. what the grid itself costs.")
    L.append("")
    L.append("| alpha | sep | exact I_AB | package inter | d_headline | d_partition"
             " | d_grid | %E_NL | %I_AB | resolved by U? |")
    L.append("|---|" * 10)
    for r in rows:
        res = ("yes (%.0f x U)" % (abs(r["d_headline"]) / unc)
               if unc == unc and abs(r["d_headline"]) > unc
               else ("no" if unc == unc else "n/a"))
        L.append("| %.1f | %.1f | %.4e | %.4e | %+.3e | %+.3e | %+.3e | %+.3f | "
                 "%+.2f | %s |"
                 % (r["alpha"], r["sep"], r["I_AB"], r["grid_inter"],
                    r["d_headline"], r["d_partition_prod"], r["d_grid_error"],
                    100 * r["rel_to_term"], 100 * r["rel_to_cross"], res))
    d = [r["d_headline"] for r in rows]
    dp = [r["d_partition_prod"] for r in rows]
    dg = [r["d_grid_error"] for r in rows]
    L.append("")
    L.append("- d_headline: min-abs %.3e  median %.3e  max-abs %.3e Ha"
             "  (= %.5f / %.5f / %.5f kcal/mol)"
             % (min(d, key=abs), float(np.median(d)), max(d, key=abs),
                min(d, key=abs) * KCAL, float(np.median(d)) * KCAL,
                max(d, key=abs) * KCAL))
    L.append("- d_partition (grid cancels): min-abs %.3e  median %.3e  max-abs %.3e Ha"
             % (min(dp, key=abs), float(np.median(dp)), max(dp, key=abs)))
    L.append("- d_grid (the grid's own cost in the same quantity): min-abs %.3e"
             "  median %.3e  max-abs %.3e Ha"
             % (min(dg, key=abs), float(np.median(dg)), max(dg, key=abs)))
    L.append("- share of the whole VV10 term: min %.4f%%  median %.4f%%  max %.4f%%"
             % (100 * min(abs(r["rel_to_term"]) for r in rows),
                100 * float(np.median([r["rel_to_term"] for r in rows])),
                100 * max(abs(r["rel_to_term"]) for r in rows)))
    L.append("- share of the cross term it is meant to be: min %.3f%%  median %.3f%%"
             "  max %.3f%%"
             % (100 * min(abs(r["rel_to_cross"]) for r in rows),
                100 * float(np.median([r["rel_to_cross"] for r in rows])),
                100 * max(abs(r["rel_to_cross"]) for r in rows)))
    if unc == unc:
        nres = sum(1 for x in d if abs(x) > unc)
        L.append("- resolved (|d_headline| > U): %d of %d configurations"
                 % (nres, len(d)))
    # A second, independent error bar.  U bounds the *deterministic* reference's own
    # quadrature error and is dominated by the 3-D vs 5-D disagreement; the Monte-Carlo
    # route bounds a different estimator's total error (its statistical s.e. plus the
    # observed MC-vs-5-D gap).  mc_tighten.py writes it to a separate sidecar so the two
    # archived runs stay byte-identical; if the sidecar is absent this section is simply
    # omitted rather than guessed at.
    mc_path = os.path.join(OUT, "mc_tight.json")
    if os.path.exists(mc_path):
        with open(mc_path, encoding="utf-8") as fh:
            mc = json.load(fh)
        comb = {(x["alpha"], x["sep"]): max(2.0 * x["mc_se_ha"],
                                            abs(x["cross_check_vs_5d_ha"]))
                for x in mc["rows"]}
        have = [r for r in rows if (r["alpha"], r["sep"]) in comb]
        if have:
            bars = [comb[(r["alpha"], r["sep"])] for r in have]
            nmc = sum(1 for r in have if abs(r["d_headline"]) > comb[(r["alpha"], r["sep"])])
            L.append("- second, independent bar from the Monte-Carlo route"
                     " (`mc_tighten.py`, %d draws per configuration): per configuration"
                     " max(2 s.e., |MC - 5-D|); worst %.3e Ha = %.5f kcal/mol, i.e. %.1f x"
                     " tighter than U"
                     % (mc["meta"]["m_per_config"], max(bars), max(bars) * KCAL,
                        unc / max(bars)))
            L.append("- resolved against the Monte-Carlo bar: %d of %d configurations"
                     " (against U: %d of %d). The two numbers answer different questions"
                     " and a configuration is only called resolved against the bar named"
                     " with it." % (nmc, len(have), nres if unc == unc else -1, len(rows)))
    L.append("- Monte-Carlo z-scores on I_AB across configurations: worst |z| = %.2f"
             % max(abs(r["mc_z"]) for r in rows))
    L.append("- closure |1/2 sum(I_XY) - undecomposed total|: worst %.3e Ha"
             % max(r["closure"] for r in rows))
    L.append("- symmetry |I_BB - I_AA| / |I_BA - I_AB|: worst %.3e / %.3e Ha"
             % (max(r["sym_aa_bb"] for r in rows), max(r["sym_ab_ba"] for r in rows)))
    L.append("- package additivity residual (sum of blocks minus its own pair sum):"
             " worst %.3e Ha" % max(abs(r["additivity"]) for r in rows))
    L.append("- node-set normalisation (expected %.1f electrons): production grid"
             " range %.8f..%.8f, referee nodes range %.8f..%.8f"
             % (2 * meta["n_elec_per_gaussian"],
                min(r["grid_electrons"] for r in rows),
                max(r["grid_electrons"] for r in rows),
                min(r["box_electrons"] for r in rows),
                max(r["box_electrons"] for r in rows)))
    L.append("- runtime %.0f s on %d workers" % (meta["runtime_s"], meta["nproc"]))
    with open(os.path.join(OUT, "summary.md"), "w") as fh:
        fh.write("\n".join(L) + "\n")
    print("wrote outputs/summary.md")
    print("\n".join(L[:2]))


if __name__ == "__main__":
    main()
